### ISSUE TITLE
Caspersplash on 10.11 clients

### ISSUE THREAD

**Issue by riddl0rd** [ftiff/CasperSplash#9]
20/12/16 13:28:40,250 CasperSplash[94536]: Failed to connect (colorGridView) outlet from (NSApplication) to (NSColorPickerGridView): missing setter or instance variable
20/12/16 13:28:40,250 CasperSplash[94536]: Failed to connect (view) outlet from (NSApplication) to (NSColorPickerGridView): missing setter or instance variable

Looks like in this new version caspersplash can't be run on 10.11 clients.
10.12 works fine btw.

**Comment by ftiff** [comment]
Should be fixed in https://github.com/ftiff/CasperSplash/tree/fix-9

@riddl0rd Please test!
[CasperSplash fix-9.zip](https://github.com/ftiff/CasperSplash/files/664144/CasperSplash.fix-9.zip)

**Comment by ftiff** [comment]
solved
